name: "Little HIVE"
description: "Musings of an independent developer"
url: "http://joedono.github.io"
paginate: 5
paginate_path: "/page/:num"
permalink: "/post/:year/:year-:month-:day-:title:output_ext"
exclude: [package.json, package-lock.json, README.md, RUNME.bat, RUNME.js, node_modules]
gems: [jekyll-paginate]
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: "category"
            type: "pages"
        values:
            layout: "category"
